# Target
target:
  icarus_connector:

# Strategy
strategy:
  type: custom
  module: ares_llm_attacker.assets.strategies.strategy
  class: LLMAttackerStrategy

red-teaming:
  intent: my_multi_turn_intent
  prompts: ./assets/seeds.csv

my_multi_turn_intent:
  strategy:
    multi-turn:
      max_turns: 15
      input_path: assets/attack_goals.json
      type: strategies.strategy
      output_path: results/strategy_results.json
      agent_config_path: assets/agent_config.yaml

output:
  dir: results/llm-attacker
  save_responses: true
  save_prompts: true
