[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ares-dynamic-llm"
version = "0.3.0"
description = "ARES Template for Dynamic LLM-to-LLM attack plugin"
authors = [
    {name = "Ibrahim Malik", email = "Ibrahim.Malik@ibm.com"},
    {name = "Cristian Morasso", email = "Cristian.Morasso@ibm.com"},
    {name = "Emile Aydar", email = "Emile.Aydar@ibm.com"}
]
readme = "README.md"
requires-python = ">=3.11"
license = {text = "Apache-2.0"}
keywords = ["ares", "red-teaming", "llm", "jailbreak", "security"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Security",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "langchain-ollama>=0.1.0",
    "langchain>=0.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov",
]

[project.urls]
Homepage = "https://github.com/ibrahimssmalik/ares-llm-attacker"
Repository = "https://github.com/IBM/ares"
Issues = "https://github.com/IBM/ares/issues"

[tool.setuptools]
packages = {find = {where = ["src"]}}

[tool.setuptools.package-data]
ares_llm_attacker = [
    "assets/*.yaml",
    "assets/*.csv",
    "assets/*.json",
]